name: doctorapp
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  country_pickers:
  flutter_svg_provider: ^1.0.7
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  pin_code_fields: ^8.0.1

  pin_input_text_field: ^4.5.2
  colorful_safe_area: ^1.0.0
  intl: ^0.19.0
  pinput: ^5.0.0
  flutter_riverpod: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNovaBold.ttf
          weight: 700
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirBlack.ttf
          weight: 900
        - asset: assets/fonts/AvenirHeavy.ttf
          weight: 900
        - asset: assets/fonts/AvenirRegular.ttf
          weight: 400
        - asset: assets/fonts/AvenirMedium.ttf
          weight: 500
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 700
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
    - family: OCR A Extended
      fonts:
        - asset: assets/fonts/OCRAExtended.ttf
          weight: 400
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSansMedium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansBold.ttf
          weight: 700
    - family: Outfit
      fonts:
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
